// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenSourceURL(arg1:string):Promise<void>;

export function SaveConfigVar(arg1:string,arg2:any):Promise<void>;

export function SelectFolder(arg1:string):Promise<string>;

export function StartConversion(arg1:string,arg2:string):Promise<void>;
