// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenSourceURL(arg1) {
  return window['go']['main']['App']['OpenSourceURL'](arg1);
}

export function SaveConfigVar(arg1, arg2) {
  return window['go']['main']['App']['SaveConfigVar'](arg1, arg2);
}

export function SelectFolder(arg1) {
  return window['go']['main']['App']['SelectFolder'](arg1);
}

export function StartConversion(arg1, arg2) {
  return window['go']['main']['App']['StartConversion'](arg1, arg2);
}
